language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

after_success:
  - "find dist -name '*' -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST$FTP_REMOTE_ROOT/{} \\;"
