language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run generate

before_install:
  - chmod +x deploy.sh
  - apt install -y lftp

script:
  - echo "Skipping tests"

after_success:
  - sh deploy.sh
