language: node_js
node_js:
  - "10"

install:
  - npm install
  - npm run generate

after_success:
  - "find dist -name '*' -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST$FTP_REMOTE_ROOT/{} \\;"
